/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EarthSciML Serialization Format (v0.2.0) — a language-agnostic JSON format for Earth system model components, their composition, and runtime configuration. v0.2.0 promotes boundary_conditions from a domain property to a first-class model-level section (see docs/rfcs/discretization.md §9). Files declaring domains.<d>.boundary_conditions are no longer valid under this schema and must be migrated via the spec.migrate_0_1_to_0_2 convention (RFC §16.1).
 */
export type ESMFormat = ESMFormat1 & ESMFormat2;
export type ESMFormat1 = {
  [k: string]: unknown;
};
/**
 * A variable in an ODE/SDE model.
 */
export type ModelVariable = ModelVariable1 & {
  /**
   * state = time-dependent unknown; parameter = externally set constant; observed = derived quantity; brownian = stochastic noise process (Wiener) that drives an SDE — the presence of any brownian variable promotes the enclosing model from an ODE system to an SDE system.
   */
  type: "state" | "parameter" | "observed" | "brownian";
  units?: string;
  default?: number;
  /**
   * Units of the default value, if different from the declared units field. When present, validators flag a unit_inconsistency error if these do not match the declared units (including dimensionally incompatible cases like K vs kg, and same-dimension mismatches like K vs degC). Default is the same as `units`.
   */
  default_units?: string;
  description?: string;
  /**
   * Defining expression for observed variables.
   */
  expression?: number | string | ExpressionNode;
  /**
   * Arrayed-variable shape: ordered list of dimension names (drawn from the enclosing model's domain.spatial). Omitted or null indicates a scalar. Introduced in spec 0.2 (discretization RFC §10.2).
   */
  shape?: string[];
  /**
   * Staggered-grid location tag (e.g., "cell_center", "edge_normal", "x_face", "vertex"). Omitted indicates no explicit staggering; the spatialization step defaults to "cell_center" when the variable's model has a grid (discretization RFC §10.2, §11 step 2).
   */
  location?: string;
  /**
   * Brownian-only: kind of stochastic process. Currently only "wiener" (zero-mean unit-variance Gaussian increments) is supported; reserved for future extension to "colored", "correlated", etc.
   */
  noise_kind?: "wiener";
  /**
   * Brownian-only: optional opaque tag used to group correlated noise sources. Brownian variables sharing a group label are interpreted by the runtime as drawn from a joint multivariate normal whose correlation matrix is supplied externally. Brownian variables without a group label are independent. The spec does not currently encode the correlation matrix itself; that is left to a future extension.
   */
  correlation_group?: string;
};
export type ModelVariable1 = {
  [k: string]: unknown;
};
/**
 * An operation in the expression AST.
 */
export type ExpressionNode = ExpressionNode1 & {
  /**
   * Operator name.
   */
  op:
    | "+"
    | "-"
    | "*"
    | "/"
    | "^"
    | "D"
    | "grad"
    | "div"
    | "laplacian"
    | "exp"
    | "log"
    | "log10"
    | "sqrt"
    | "abs"
    | "sin"
    | "cos"
    | "tan"
    | "asin"
    | "acos"
    | "atan"
    | "atan2"
    | "min"
    | "max"
    | "floor"
    | "ceil"
    | "ifelse"
    | ">"
    | "<"
    | ">="
    | "<="
    | "=="
    | "!="
    | "and"
    | "or"
    | "not"
    | "Pre"
    | "sign"
    | "arrayop"
    | "makearray"
    | "index"
    | "broadcast"
    | "reshape"
    | "transpose"
    | "concat"
    | "call"
    | "bc";
  /**
   * Operand list. For most ops these are sub-expressions. Array ops use args for the input array operands (arrayop, broadcast, index, reshape, transpose, concat). makearray has no natural args and uses an empty array.
   *
   * @minItems 0
   */
  args: Expression[];
  /**
   * Differentiation variable for D operator (e.g., "t").
   */
  wrt?: string;
  /**
   * Spatial dimension for grad operator (e.g., "x", "y", "z").
   */
  dim?: string;
  /**
   * For arrayop: the result's index signature. Each entry is either a string (a symbolic index variable like "i", "j") or the integer 1 (a literal singleton dimension for reshape/broadcast). Mirrors SymbolicUtils.ArrayOp.output_idx.
   */
  output_idx?: (string | 1)[];
  /**
   * Mathematical expression: a number literal, a variable/parameter reference string, or an operator node.
   */
  expr?: number | string | ExpressionNode1;
  /**
   * For arrayop: the reduction operator applied to any index symbol that appears in expr but not in output_idx. Default is "+".
   */
  reduce?: "+" | "*" | "max" | "min";
  /**
   * For arrayop: optional map from index symbol name to the range it iterates over. Each value is either a 2-element array [start, stop] (unit step) or a 3-element array [start, step, stop]. Indices not present are inferred from the domain / operand shapes at runtime. Mirrors SymbolicUtils.ArrayOp.ranges.
   */
  ranges?: {
    /**
     * @minItems 2
     * @maxItems 3
     */
    [k: string]: [number, number] | [number, number, number];
  };
  /**
   * For makearray: list of sub-region boxes of the output array. Each region is an array of [start, stop] pairs, one per output dimension. The nth region is filled with the nth entry of values. Overlapping regions are permitted; later regions overwrite earlier ones. Mirrors SymbolicUtils.ArrayMaker.regions.
   */
  regions?: [[number, number], ...[number, number][]][];
  /**
   * For makearray: list of expressions, one per entry in regions. Each value may be a scalar expression (broadcast across the region) or an array-valued expression whose shape matches the region (excluding singleton dimensions). Mirrors SymbolicUtils.ArrayMaker.values.
   */
  values?: Expression[];
  /**
   * For reshape: the target shape. Each entry is either an integer (a concrete length) or a string (a symbolic dimension reference).
   *
   * @minItems 1
   */
  shape?: [number | string, ...(number | string)[]];
  /**
   * For transpose: optional axis permutation. A list of 0-based axis indices giving the new order. If omitted, the matrix-transpose convention is used (reverse axes).
   */
  perm?: number[];
  /**
   * For concat: the 0-based axis along which to concatenate the operand arrays. All operands must have identical shape on every other axis.
   */
  axis?: number;
  /**
   * For broadcast: the name of the scalar operator to apply element-wise to the operands in args. Must be an ExpressionNode op name drawn from the scalar subset (arithmetic, elementary functions, comparisons, etc.).
   */
  fn?: string;
  /**
   * For call: the identifier of a registered function (a key in the top-level `registered_functions` map). The handler receives the evaluated `args` positionally.
   */
  handler_id?: string;
  /**
   * For the 'bc' pattern-match op: the BC kind to match (one of 'constant', 'dirichlet', 'neumann', 'robin', 'zero_gradient', 'periodic', 'flux_contrib'). See RFC §9.2.
   */
  kind?: "constant" | "dirichlet" | "neumann" | "robin" | "zero_gradient" | "periodic" | "flux_contrib";
  /**
   * For the 'bc' pattern-match op: the BC side to match (e.g., 'xmin', 'xmax', 'ymin', 'panel_seam', 'mesh_boundary'). See RFC §9.2.
   */
  side?: string;
};
export type ExpressionNode1 = {
  [k: string]: unknown;
};
/**
 * Mathematical expression: a number literal, a variable/parameter reference string, or an operator node.
 */
export type Expression = number | string | ExpressionNode1;
/**
 * Fires when a boolean condition is true at end of a timestep, or at preset/periodic times. Maps to MTK SymbolicDiscreteCallback.
 */
export type DiscreteEvent = {
  /**
   * Human-readable identifier.
   */
  name?: string;
  trigger: DiscreteEventTrigger;
  /**
   * Affect equations. Required unless functional_affect is used.
   */
  affects?: AffectEquation[];
  functional_affect?: FunctionalAffect;
  /**
   * Parameters modified by this event. Required when affects modify parameters rather than state variables.
   */
  discrete_parameters?: string[];
  /**
   * Whether to reinitialize the system after the event.
   */
  reinitialize?: boolean;
  description?: string;
} & DiscreteEvent1;
/**
 * Trigger specification for a discrete event.
 */
export type DiscreteEventTrigger =
  | {
      type: "condition";
      expression: Expression;
    }
  | {
      type: "periodic";
      /**
       * Interval in simulation time units.
       */
      interval: number;
      /**
       * Offset from t=0 for the first firing.
       */
      initial_offset?: number;
    }
  | {
      type: "preset_times";
      /**
       * Array of simulation times at which to fire.
       *
       * @minItems 1
       */
      times: [number, ...number[]];
    };
export type DiscreteEvent1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * One axis of a parameter sweep: exactly one of values or range must be given.
 */
export type SweepDimension = {
  /**
   * Name of the parameter to vary (local to this component).
   */
  parameter: string;
  /**
   * Enumerated values to use for this axis.
   *
   * @minItems 1
   */
  values?: [number, ...number[]];
  range?: SweepRange;
} & SweepDimension1;
export type SweepDimension1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * A single coupling rule connecting models, reaction systems, data loaders, or operators.
 */
export type CouplingEntry =
  | CouplingOperatorCompose
  | CouplingCouple
  | CouplingVariableMap
  | CouplingOperatorApply
  | CouplingCallback
  | CouplingEvent;
/**
 * Translation target: a simple variable reference string or an object with var and factor.
 */
export type TranslateTarget =
  | string
  | {
      var: string;
      factor?: number;
    };
/**
 * Cross-system event involving variables from multiple coupled systems.
 */
export type CouplingEvent = CouplingEvent1 & {
  type: "event";
  /**
   * Whether this is a continuous or discrete event.
   */
  event_type: "continuous" | "discrete";
  /**
   * Human-readable identifier.
   */
  name?: string;
  /**
   * Condition expressions (zero-crossing for continuous, boolean for discrete).
   */
  conditions?: Expression[];
  /**
   * Trigger specification for a discrete event.
   */
  trigger?:
    | {
        type: "condition";
        expression: Expression;
      }
    | {
        type: "periodic";
        /**
         * Interval in simulation time units.
         */
        interval: number;
        /**
         * Offset from t=0 for the first firing.
         */
        initial_offset?: number;
      }
    | {
        type: "preset_times";
        /**
         * Array of simulation times at which to fire.
         *
         * @minItems 1
         */
        times: [number, ...number[]];
      };
  /**
   * Affect equations. Required unless functional_affect is used.
   */
  affects?: AffectEquation[];
  functional_affect?: FunctionalAffect1;
  affect_neg?: null | AffectEquation[];
  discrete_parameters?: string[];
  root_find?: "left" | "right" | "all";
  reinitialize?: boolean;
  description?: string;
} & CouplingEvent2;
export type CouplingEvent1 = {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
export type CouplingEvent2 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * Initial conditions for state variables.
 */
export type InitialConditions =
  | {
      type: "constant";
      value: number;
    }
  | {
      type: "per_variable";
      values: {
        [k: string]: number;
      };
    }
  | {
      type: "from_file";
      path: string;
      format?: string;
    };
/**
 * A named discretization grid. The `family` selects one of three topologies (cartesian / unstructured / cubed_sphere) per docs/rfcs/discretization.md §6.1-§6.4. Each grid also carries optional staggering locations, metric array declarations, and its own parameter block reusing the ordinary ESM Parameter schema.
 */
export type Grid = Grid1 & {
  family: "cartesian" | "unstructured" | "cubed_sphere";
  description?: string;
  /**
   * Ordered list of logical dimension names.
   *
   * @minItems 1
   */
  dimensions: [string, ...string[]];
  /**
   * Declared stagger locations used by variables on this grid (see §11).
   */
  locations?: string[];
  metric_arrays?: {
    [k: string]: GridMetricArray;
  };
  /**
   * Grid-level parameters. Reuses the ordinary ESM Parameter schema. Parameters with value='from_loader' are resolved at load time from a referenced data_loaders entry (§6.6).
   */
  parameters?: {
    [k: string]: Parameter;
  };
  /**
   * Optional name of the domains entry this grid refines. If a domain declares grid_spacing for the same dimension, the grid's extents.<dim>.spacing wins (§6.1).
   */
  domain?: string;
  /**
   * Per-dimension extents. Required for 'cartesian' and 'cubed_sphere'; not used by 'unstructured'.
   */
  extents?: {
    [k: string]: GridExtent;
  };
  /**
   * Unstructured-family connectivity tables. Keys are table names (e.g., cellsOnEdge). Required for 'unstructured'; forbidden otherwise.
   */
  connectivity?: {
    [k: string]: GridConnectivity;
  };
  /**
   * Cubed-sphere panel_connectivity tables (e.g., neighbors, axis_flip). Required for 'cubed_sphere'; forbidden otherwise. Typically built from the gnomonic_c6_* builtins.
   */
  panel_connectivity?: {
    [k: string]: GridConnectivity;
  };
};
export type Grid1 = {
  [k: string]: unknown;
};
/**
 * Generator for a grid metric array. Exactly one kind per §6.5: 'expression' (analytic, computed at discretization time from grid parameters), 'loader' (pulled from a named data_loaders entry), or 'builtin' (from a closed set of canonical tables — currently 'gnomonic_c6_neighbors' and 'gnomonic_c6_d4_action'; adding a new builtin is a minor version bump per §6.4.1).
 */
export type GridMetricGenerator = GridMetricGenerator1 & {
  kind: "expression" | "loader" | "builtin";
  /**
   * For kind='expression': an ESM expression. All free variables must be grid parameters or dimension indices.
   */
  expr?: number | string | ExpressionNode1;
  /**
   * For kind='loader': name of a data_loaders entry that produces the array.
   */
  loader?: string;
  /**
   * For kind='loader': named field within the referenced loader's output.
   */
  field?: string;
  /**
   * For kind='builtin': canonical name from the closed set defined in §6.4 (currently 'gnomonic_c6_neighbors', 'gnomonic_c6_d4_action'). Unknown names MUST be rejected with E_UNKNOWN_BUILTIN.
   */
  name?: string;
};
export type GridMetricGenerator1 = {
  [k: string]: unknown;
};
/**
 * Generator for a grid metric array. Exactly one kind per §6.5: 'expression' (analytic, computed at discretization time from grid parameters), 'loader' (pulled from a named data_loaders entry), or 'builtin' (from a closed set of canonical tables — currently 'gnomonic_c6_neighbors' and 'gnomonic_c6_d4_action'; adding a new builtin is a minor version bump per §6.4.1).
 */
export type GridMetricGenerator2 = {
  [k: string]: unknown;
} & {
  kind: "expression" | "loader" | "builtin";
  /**
   * For kind='expression': an ESM expression. All free variables must be grid parameters or dimension indices.
   */
  expr?: number | string | ExpressionNode1;
  /**
   * For kind='loader': name of a data_loaders entry that produces the array.
   */
  loader?: string;
  /**
   * For kind='loader': named field within the referenced loader's output.
   */
  field?: string;
  /**
   * For kind='builtin': canonical name from the closed set defined in §6.4 (currently 'gnomonic_c6_neighbors', 'gnomonic_c6_d4_action'). Unknown names MUST be rejected with E_UNKNOWN_BUILTIN.
   */
  name?: string;
};

export interface ESMFormat2 {
  /**
   * Format version string (semver).
   */
  esm: string;
  metadata: Metadata;
  /**
   * ODE-based model components, keyed by unique identifier.
   */
  models?: {
    [k: string]: Model;
  };
  /**
   * Reaction network components, keyed by unique identifier.
   */
  reaction_systems?: {
    [k: string]: ReactionSystem;
  };
  /**
   * External data source registrations (by reference).
   */
  data_loaders?: {
    [k: string]: DataLoader;
  };
  /**
   * Registered runtime operators (by reference).
   */
  operators?: {
    [k: string]: Operator;
  };
  /**
   * Registry of named pure functions that may be invoked inside expressions via the 'call' op. Each entry names a handler the runtime binds to a concrete implementation (e.g. an interpolation table lookup, a @register_symbolic stub in Julia).
   */
  registered_functions?: {
    [k: string]: RegisteredFunction;
  };
  /**
   * Composition and coupling rules.
   */
  coupling?: CouplingEntry[];
  /**
   * Named spatial/temporal domain specifications.
   */
  domains?: {
    [k: string]: Domain;
  };
  /**
   * Geometric connections between domains of different dimensionality.
   */
  interfaces?: {
    [k: string]: Interface;
  };
  /**
   * Named discretization grids (v0.2.0). Each entry declares a cartesian/unstructured/cubed_sphere topology with dimensions, staggering locations, metric arrays, and (for unstructured/cubed-sphere) connectivity tables. See docs/rfcs/discretization.md §6.
   */
  grids?: {
    [k: string]: Grid;
  };
}
/**
 * Authorship, provenance, and description.
 */
export interface Metadata {
  /**
   * Short identifier for the model configuration.
   */
  name: string;
  description?: string;
  authors?: string[];
  license?: string;
  /**
   * ISO 8601 creation timestamp.
   */
  created?: string;
  /**
   * ISO 8601 last-modified timestamp.
   */
  modified?: string;
  tags?: string[];
  references?: Reference[];
}
/**
 * Academic citation or data source reference.
 */
export interface Reference {
  doi?: string;
  citation?: string;
  url?: string;
  notes?: string;
}
/**
 * An ODE system — a fully specified set of time-dependent equations.
 */
export interface Model {
  /**
   * Name of a domain from the domains section. Omit or set to null for 0D (non-spatial) models.
   */
  domain?: string | null;
  /**
   * Coupling type name. Informational label identifying this system's role in coupling.
   */
  coupletype?: string | null;
  reference?: Reference;
  /**
   * All variables, keyed by name.
   */
  variables: {
    [k: string]: ModelVariable;
  };
  /**
   * Array of {lhs, rhs} equation objects.
   */
  equations: Equation[];
  discrete_events?: DiscreteEvent[];
  continuous_events?: ContinuousEvent[];
  /**
   * Named child models (subsystems), keyed by unique identifier. Enables hierarchical model composition. Variables in subsystems are referenced via dot notation: "ParentModel.ChildModel.var". Each subsystem can be defined inline or included by reference via a local file path or URL.
   */
  subsystems?: {
    [k: string]: Model | SubsystemRef;
  };
  tolerance?: Tolerance;
  /**
   * Inline validation tests that exercise this model in isolation. Each test specifies initial conditions, parameter overrides, a time span, and scalar assertions at specific (variable, time) points.
   */
  tests?: Test[];
  /**
   * Inline illustrative examples of how to run this model. Each example specifies initial state, parameters, a time span, an optional parameter sweep, and plot specifications.
   */
  examples?: Example[];
  /**
   * Model-level boundary conditions, keyed by user-supplied id (see docs/rfcs/discretization.md §9). v0.2.0 breaking change: domains.<d>.boundary_conditions was removed in favor of this field; files from v0.1.0 carrying the old field must be migrated via spec.migrate_0_1_to_0_2 (RFC §16.1).
   */
  boundary_conditions?: {
    [k: string]: BoundaryCondition;
  };
}
/**
 * An equation: lhs = rhs (or lhs ~ rhs in MTK notation).
 */
export interface Equation {
  lhs: Expression;
  rhs: Expression;
  _comment?: string;
}
/**
 * An affect equation in an event: lhs is the target variable (string), rhs is an expression.
 */
export interface AffectEquation {
  /**
   * Target variable name (value after the event).
   */
  lhs: string;
  /**
   * Mathematical expression: a number literal, a variable/parameter reference string, or an operator node.
   */
  rhs: number | string | ExpressionNode1;
}
/**
 * Registered functional affect handler (alternative to symbolic affects).
 */
export interface FunctionalAffect {
  /**
   * Registered identifier for the affect implementation.
   */
  handler_id: string;
  /**
   * State variables accessed by the handler.
   */
  read_vars: string[];
  /**
   * Parameters accessed by the handler.
   */
  read_params: string[];
  /**
   * Parameters modified by the handler (implicitly discrete parameters).
   */
  modified_params?: string[];
  /**
   * Handler-specific configuration.
   */
  config?: {
    [k: string]: unknown;
  };
}
/**
 * Fires when a condition expression crosses zero (root-finding). Maps to MTK SymbolicContinuousCallback.
 */
export interface ContinuousEvent {
  /**
   * Human-readable identifier.
   */
  name?: string;
  /**
   * Expressions that trigger the event when they cross zero.
   *
   * @minItems 1
   */
  conditions: [Expression, ...Expression[]];
  /**
   * Affect equations applied on positive-going zero crossings (or both directions if affect_neg is absent). Empty array for pure detection.
   */
  affects: AffectEquation[];
  /**
   * Separate affects for negative-going zero crossings. If null or absent, affects is used for both directions.
   */
  affect_neg?: null | AffectEquation[];
  /**
   * Root-finding direction.
   */
  root_find?: "left" | "right" | "all";
  /**
   * Whether to reinitialize the system after the event.
   */
  reinitialize?: boolean;
  description?: string;
}
/**
 * A reference to an external ESM file containing a model or reaction system definition. The ref field can be a relative or absolute local file path, or an HTTP/HTTPS URL. Relative paths are resolved relative to the directory of the referencing file.
 */
export interface SubsystemRef {
  /**
   * Local file path or URL pointing to an ESM file. The referenced file must contain exactly one top-level model or reaction system, which is used as the subsystem definition.
   */
  ref: string;
}
/**
 * Model-level default numerical tolerance for tests, used when a test or assertion does not provide its own.
 */
export interface Tolerance {
  /**
   * Absolute tolerance: |actual - expected| <= abs.
   */
  abs?: number;
  /**
   * Relative tolerance: |actual - expected| / max(|expected|, epsilon) <= rel.
   */
  rel?: number;
}
/**
 * An inline validation test for the enclosing model or reaction system. Defines the run configuration (initial conditions, parameter overrides, time span) and the scalar assertions that must hold.
 */
export interface Test {
  /**
   * Identifier unique within this component's tests array.
   */
  id: string;
  /**
   * Human-readable description of what this test verifies.
   */
  description?: string;
  /**
   * Initial-value overrides for state variables, keyed by variable name (local to this component). Values not listed fall back to the variable's declared default.
   */
  initial_conditions?: {
    [k: string]: number;
  };
  /**
   * Parameter overrides, keyed by parameter name (local to this component). Values not listed fall back to the parameter's declared default.
   */
  parameter_overrides?: {
    [k: string]: number;
  };
  time_span: TimeSpan;
  tolerance?: Tolerance1;
  /**
   * Scalar (variable, time) checks that define the pass/fail criterion of the test.
   *
   * @minItems 1
   */
  assertions: [Assertion, ...Assertion[]];
}
/**
 * Simulation time interval expressed in the component's time units.
 */
export interface TimeSpan {
  start: number;
  end: number;
}
/**
 * Test-level default tolerance applied to all assertions in this test that do not override it.
 */
export interface Tolerance1 {
  /**
   * Absolute tolerance: |actual - expected| <= abs.
   */
  abs?: number;
  /**
   * Relative tolerance: |actual - expected| / max(|expected|, epsilon) <= rel.
   */
  rel?: number;
}
/**
 * A single scalar check at a (variable, time) point.
 */
export interface Assertion {
  /**
   * Name of the variable or species to check. Use the local name (e.g., "O3") or a scoped reference relative to this component (e.g., "subsystem.X").
   */
  variable: string;
  /**
   * Simulation time at which to evaluate the assertion. Must lie within [time_span.start, time_span.end].
   */
  time: number;
  /**
   * Expected scalar value of the variable at the given time.
   */
  expected: number;
  tolerance?: Tolerance2;
}
/**
 * Per-assertion tolerance override. If present, this takes precedence over the test-level and model-level defaults.
 */
export interface Tolerance2 {
  /**
   * Absolute tolerance: |actual - expected| <= abs.
   */
  abs?: number;
  /**
   * Relative tolerance: |actual - expected| / max(|expected|, epsilon) <= rel.
   */
  rel?: number;
}
/**
 * An inline illustrative example of how to run the enclosing component. Defines the run configuration and one or more plots derived from the result.
 */
export interface Example {
  /**
   * Identifier unique within this component's examples array.
   */
  id: string;
  /**
   * Human-readable description of what this example illustrates.
   */
  description?: string;
  /**
   * Initial conditions for state variables. Reuses the top-level InitialConditions $def (constant / per_variable / from_file).
   */
  initial_state?:
    | {
        type: "constant";
        value: number;
      }
    | {
        type: "per_variable";
        values: {
          [k: string]: number;
        };
      }
    | {
        type: "from_file";
        path: string;
        format?: string;
      };
  /**
   * Parameter overrides, keyed by parameter name (local to this component).
   */
  parameters?: {
    [k: string]: number;
  };
  time_span: TimeSpan;
  parameter_sweep?: ParameterSweep;
  /**
   * Plot specifications derived from this example's run(s).
   */
  plots?: Plot[];
}
/**
 * Optional parameter sweep. When present, the example represents a family of runs (one per Cartesian combination) rather than a single trajectory.
 */
export interface ParameterSweep {
  /**
   * Sweep combination strategy. Currently only cartesian (full Cartesian product) is supported.
   */
  type: "cartesian";
  /**
   * @minItems 1
   */
  dimensions: [SweepDimension, ...SweepDimension1[]];
}
/**
 * Generated range; mutually exclusive with values.
 */
export interface SweepRange {
  start: number;
  stop: number;
  count: number;
  /**
   * Spacing: linear = evenly spaced between start and stop; log = logarithmically spaced (start and stop must be strictly positive).
   */
  scale?: "linear" | "log";
}
/**
 * A plot specification associated with an example. Only structural information is recorded — axes, series selection, and value reductions. Styling (colors, fonts, legends, themes) is the viewer's concern.
 */
export interface Plot {
  /**
   * Identifier unique within this example's plots array.
   */
  id: string;
  type: "line" | "scatter" | "heatmap";
  description?: string;
  x: PlotAxis;
  y: PlotAxis;
  value?: PlotValue;
  /**
   * Multiple named series for line or scatter plots. Ignored for heatmap.
   */
  series?: PlotSeries[];
}
/**
 * Axis specification: any state variable, observed variable, parameter name, or swept parameter may be used.
 */
export interface PlotAxis {
  /**
   * Variable or parameter name (local to this component or scoped within a subsystem).
   */
  variable: string;
  /**
   * Human-readable axis label. Viewers should fall back to the variable name if omitted.
   */
  label?: string;
}
/**
 * Required for heatmap; defines the color channel. Ignored for line/scatter.
 */
export interface PlotValue {
  /**
   * Variable whose trajectory is reduced to a scalar per run.
   */
  variable: string;
  /**
   * Specific simulation time at which to sample the variable.
   */
  at_time?: number;
  /**
   * Time-reduction applied to the trajectory: max/min/mean over the run, time integral, or the final value at time_span.end.
   */
  reduce?: "max" | "min" | "mean" | "integral" | "final";
}
/**
 * A single named series for multi-series line or scatter plots.
 */
export interface PlotSeries {
  name: string;
  variable: string;
}
/**
 * Model-level boundary condition entry (v0.2.0). Constrains one model variable on one boundary side. See docs/rfcs/discretization.md §9.2 for full semantics. This object lives under models.<M>.boundary_conditions keyed by user-supplied id; it replaces the v0.1.0 domains.<d>.boundary_conditions list.
 */
export interface BoundaryCondition {
  /**
   * Name of the model variable the BC constrains. Must resolve to a variable declared in the enclosing model's variables map (or a dot-qualified subsystem variable).
   */
  variable: string;
  /**
   * Boundary side the BC applies to. Closed-vocabulary axis sides ('xmin', 'xmax', 'ymin', 'ymax', 'zmin', 'zmax', 'tmin', 'tmax'), grid-family-specific seams ('panel_seam' for cubed-sphere), or generic unstructured boundary markers ('mesh_boundary'). Authors MAY introduce additional named sides (e.g., 'north', 'surface') provided the grid they reference declares them.
   */
  side: string;
  /**
   * BC kind. constant/dirichlet = fixed value; zero_gradient/neumann = ∂u/∂n-based; robin = αu + β∂u/∂n = γ; periodic = pair-side wraparound (declare once per periodic pair on either min or max side); flux_contrib = a component-contributed flux summand that the rewrite engine aggregates with other flux_contrib entries for the same (variable, side) pair before applying the enclosing neumann/robin template.
   */
  kind: "constant" | "dirichlet" | "neumann" | "robin" | "zero_gradient" | "periodic" | "flux_contrib";
  /**
   * BC value: numeric literal, variable/parameter reference string, or expression AST. Required for kind='constant' and kind='dirichlet'; semantics for other kinds per RFC §9.2.
   */
  value?: number | string | ExpressionNode1;
  /**
   * Robin BC coefficient α for the u term in αu + β∂u/∂n = γ.
   */
  robin_alpha?: number | string | ExpressionNode1;
  /**
   * Robin BC coefficient β for the ∂u/∂n term in αu + β∂u/∂n = γ.
   */
  robin_beta?: number | string | ExpressionNode1;
  /**
   * Robin BC RHS value γ in αu + β∂u/∂n = γ.
   */
  robin_gamma?: number | string | ExpressionNode1;
  /**
   * Reduced face-coordinate index names used when `value` contains an `index` op into a loader-provided time-varying field (§9.2 / §8.A.3). E.g., for side='zmin' on a 3D grid, face_coords: ['i', 'j']. Omit when `value` does not index into a time-varying loader field.
   */
  face_coords?: string[];
  /**
   * Optional component-contribution marker identifying the model component (deposition, emissions, surface-flux scheme) providing this flux. The rewrite engine sums all flux_contrib entries for the same (variable, side) pair into a single aggregated flux, then applies the enclosing kind's BC template. See RFC §9.3.
   */
  contributed_by?: {
    /**
     * Name of the contributing component.
     */
    component: string;
    /**
     * Sign of the contribution in the aggregated flux sum. Default '+'.
     */
    flux_sign?: "+" | "-";
  };
  /**
   * Human-readable description of the BC.
   */
  description?: string;
}
/**
 * A reaction network — declarative representation of chemical or biological reactions.
 */
export interface ReactionSystem {
  /**
   * Name of a domain from the domains section. Omit or set to null for 0D (non-spatial) systems.
   */
  domain?: string | null;
  /**
   * Coupling type name. Informational label identifying this system's role in coupling.
   */
  coupletype?: string | null;
  reference?: Reference;
  /**
   * Named reactive species.
   */
  species: {
    [k: string]: Species;
  };
  /**
   * Named parameters (rate constants, temperature, photolysis rates, etc.).
   */
  parameters: {
    [k: string]: Parameter;
  };
  /**
   * Array of reaction definitions.
   *
   * @minItems 1
   */
  reactions: [Reaction, ...Reaction[]];
  /**
   * Additional algebraic or ODE constraints.
   */
  constraint_equations?: Equation[];
  discrete_events?: DiscreteEvent1[];
  continuous_events?: ContinuousEvent[];
  /**
   * Named child reaction systems (subsystems), keyed by unique identifier. Enables hierarchical system composition. Variables in subsystems are referenced via dot notation: "ParentSystem.ChildSystem.species". Each subsystem can be defined inline or included by reference via a local file path or URL.
   */
  subsystems?: {
    [k: string]: ReactionSystem | SubsystemRef;
  };
  tolerance?: Tolerance3;
  /**
   * Inline validation tests that exercise this reaction system in isolation. Each test specifies initial conditions, parameter overrides, a time span, and scalar assertions at specific (species/variable, time) points.
   */
  tests?: Test[];
  /**
   * Inline illustrative examples of how to run this reaction system. Each example specifies initial state, parameters, a time span, an optional parameter sweep, and plot specifications.
   */
  examples?: Example[];
}
/**
 * A reactive species in a reaction system.
 */
export interface Species {
  units?: string;
  default?: number;
  /**
   * Units of the default value, if different from the declared units field. See ModelVariable.default_units for semantics.
   */
  default_units?: string;
  description?: string;
}
/**
 * A parameter in a reaction system.
 */
export interface Parameter {
  units?: string;
  default?: number;
  /**
   * Units of the default value, if different from the declared units field. See ModelVariable.default_units for semantics.
   */
  default_units?: string;
  description?: string;
}
/**
 * A single reaction in a reaction system.
 */
export interface Reaction {
  /**
   * Unique reaction identifier (e.g., "R1").
   */
  id: string;
  name?: string;
  /**
   * Array of {species, stoichiometry} or null for source reactions (∅ → X).
   */
  substrates: null | [StoichiometryEntry, ...StoichiometryEntry[]];
  /**
   * Array of {species, stoichiometry} or null for sink reactions (X → ∅).
   */
  products: null | [StoichiometryEntry, ...StoichiometryEntry[]];
  /**
   * Mathematical expression: a number literal, a variable/parameter reference string, or an operator node.
   */
  rate: number | string | ExpressionNode1;
  reference?: Reference;
}
/**
 * A species with its stoichiometric coefficient in a reaction.
 */
export interface StoichiometryEntry {
  species: string;
  stoichiometry: number;
}
/**
 * System-level default numerical tolerance for tests, used when a test or assertion does not provide its own.
 */
export interface Tolerance3 {
  /**
   * Absolute tolerance: |actual - expected| <= abs.
   */
  abs?: number;
  /**
   * Relative tolerance: |actual - expected| / max(|expected|, epsilon) <= rel.
   */
  rel?: number;
}
/**
 * A generic, runtime-agnostic description of an external data source. Carries enough structural information to locate files, map timestamps to files, describe spatial/variable semantics, and regrid — rather than pointing at a runtime handler. Authentication and algorithm-specific tuning are runtime-only and not part of the schema.
 */
export interface DataLoader {
  /**
   * Structural kind of the dataset. Scientific role (emissions, meteorology, elevation, ...) is not schema-validated and belongs in metadata.tags.
   */
  kind: "grid" | "points" | "static";
  source: DataLoaderSource;
  temporal?: DataLoaderTemporal;
  spatial?: DataLoaderSpatial;
  /**
   * Variables exposed by this loader, keyed by schema-level variable name.
   */
  variables: {
    [k: string]: DataLoaderVariable;
  };
  regridding?: DataLoaderRegridding;
  reference?: Reference;
  /**
   * Free-form metadata about the data source. The "tags" field (array of strings) is conventional for expressing scientific role (e.g. "emissions", "reanalysis") and is not schema-validated.
   */
  metadata?: {
    tags?: string[];
    [k: string]: unknown;
  };
}
/**
 * File discovery configuration. Describes how to locate data files at runtime via URL templates with date/variable substitutions.
 */
export interface DataLoaderSource {
  /**
   * Jinja-style URL template with substitutions. Supported: {date:<strftime>} (e.g. {date:%Y%m%d}), {var}, {sector}, {species}. Custom substitutions are allowed and the runtime must accept and pass them through.
   */
  url_template: string;
  /**
   * Ordered fallback URL templates. Runtime tries each in order, first is primary. Follows the same substitution grammar as url_template.
   */
  mirrors?: string[];
}
/**
 * Temporal coverage and record layout for a data source.
 */
export interface DataLoaderTemporal {
  /**
   * ISO 8601 datetime — first timestamp available from this source.
   */
  start?: string;
  /**
   * ISO 8601 datetime — last timestamp available from this source.
   */
  end?: string;
  /**
   * ISO 8601 duration describing how much time one file covers (e.g., "P1D", "P1M", "PT3H").
   */
  file_period?: string;
  /**
   * ISO 8601 duration describing spacing between samples within a file.
   */
  frequency?: string;
  /**
   * Number of time records per file. "auto" means read from file at runtime.
   */
  records_per_file?: number | "auto";
  /**
   * Name of the time coordinate variable in the file. Used when records_per_file is absent or "auto". If both static declarations (records_per_file + frequency) and time_variable are present, the static declaration wins and time_variable is a fallback.
   */
  time_variable?: string;
}
/**
 * Spatial grid description for a data source.
 */
export interface DataLoaderSpatial {
  /**
   * Coordinate reference system as a PROJ string or EPSG code.
   */
  crs: string;
  /**
   * Structural grid family. Use "unstructured" for mesh/point datasets.
   */
  grid_type: "latlon" | "lambert_conformal" | "mercator" | "polar_stereographic" | "rotated_pole" | "unstructured";
  staggering?: DataLoaderStaggering;
  /**
   * Per-dimension resolution in native CRS units. Optional; some datasets only know this at runtime.
   */
  resolution?: {
    [k: string]: number;
  };
  /**
   * Per-dimension [min, max] extent in native CRS units. Optional; runtime can infer from files.
   */
  extent?: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    [k: string]: [number, number];
  };
}
/**
 * Per-dimension grid staggering (centered or edge-aligned).
 */
export interface DataLoaderStaggering {
  [k: string]: "center" | "edge";
}
/**
 * A variable exposed by a data loader, mapped from a source-file variable.
 */
export interface DataLoaderVariable {
  /**
   * Name of the variable inside the source file. May differ from the schema-level variable name.
   */
  file_variable: string;
  /**
   * Units of the variable as exposed to the schema.
   */
  units: string;
  /**
   * Optional multiplicative factor or Expression AST applied to convert source-file values to the declared units.
   */
  unit_conversion?: number | Expression;
  description?: string;
  reference?: Reference;
}
/**
 * Structural regridding configuration. Algorithm-specific tuning parameters are runtime-side and not in the schema.
 */
export interface DataLoaderRegridding {
  /**
   * Value to assign to cells with no source data.
   */
  fill_value?: number;
  /**
   * Behavior when regridding targets fall outside the source extent. Defaults to "clamp".
   */
  extrapolation?: "clamp" | "nan" | "periodic";
}
/**
 * A registered runtime operator (e.g., dry deposition, wet scavenging).
 */
export interface Operator {
  /**
   * Registered identifier the runtime uses to find the implementation.
   */
  operator_id: string;
  reference?: Reference;
  /**
   * Implementation-specific configuration.
   */
  config?: {
    [k: string]: unknown;
  };
  /**
   * Variables required by the operator.
   */
  needed_vars: string[];
  /**
   * Variables the operator modifies.
   */
  modifies?: string[];
  description?: string;
}
/**
 * A named pure function that may be invoked inside an expression via the 'call' op. Analogous to Operator, but intended for side-effect-free callables embedded directly in expression trees (e.g. interpolation handlers, Julia @register_symbolic stubs, table lookups).
 */
export interface RegisteredFunction {
  /**
   * Registered identifier. Must match the key in the `registered_functions` map and the `handler_id` used by 'call' op nodes that reference this function.
   */
  id: string;
  /**
   * Calling convention.
   */
  signature: {
    /**
     * Number of positional arguments the handler expects.
     */
    arg_count: number;
    /**
     * Optional per-argument type hints. Each entry is one of 'scalar', 'array', 'index'. When present the array length must equal arg_count.
     */
    arg_types?: ("scalar" | "array" | "index")[];
    /**
     * Optional return-type hint.
     */
    return_type?: "scalar" | "array";
  };
  /**
   * Optional output units string (same grammar as variable units).
   */
  units?: string;
  /**
   * Optional per-argument units hints. Each entry is either a units string or null (no hint). When present the array length must equal signature.arg_count.
   */
  arg_units?: (string | null)[];
  description?: string;
  references?: Reference[];
  /**
   * Implementation-specific configuration passed to the handler at bind time (e.g. table data, grid descriptors).
   */
  config?: {
    [k: string]: unknown;
  };
}
/**
 * Match LHS time derivatives and add RHS terms together.
 */
export interface CouplingOperatorCompose {
  type: "operator_compose";
  /**
   * The two systems to compose.
   *
   * @minItems 2
   * @maxItems 2
   */
  systems: [string, string];
  /**
   * Variable mappings when LHS variables don't have matching names.
   */
  translate?: {
    [k: string]: TranslateTarget;
  };
  /**
   * Name of an interface from the interfaces section for cross-domain coupling.
   */
  interface?: string;
  /**
   * Strategy for mapping between 0D and spatial systems.
   */
  lifting?: "pointwise" | "broadcast" | "mean" | "integral";
  description?: string;
}
/**
 * Bi-directional coupling via explicit ConnectorSystem equations.
 */
export interface CouplingCouple {
  type: "couple";
  /**
   * @minItems 2
   * @maxItems 2
   */
  systems: [string, string];
  connector: {
    /**
     * @minItems 1
     */
    equations: [ConnectorEquation, ...ConnectorEquation[]];
  };
  /**
   * Name of an interface from the interfaces section for cross-domain coupling.
   */
  interface?: string;
  /**
   * Strategy for mapping between 0D and spatial systems.
   */
  lifting?: "pointwise" | "broadcast" | "mean" | "integral";
  description?: string;
}
/**
 * A single equation in a ConnectorSystem linking two coupled systems.
 */
export interface ConnectorEquation {
  /**
   * Source variable (scoped reference).
   */
  from: string;
  /**
   * Target variable (scoped reference).
   */
  to: string;
  /**
   * How the expression modifies the target.
   */
  transform: "additive" | "multiplicative" | "replacement";
  /**
   * Mathematical expression: a number literal, a variable/parameter reference string, or an operator node.
   */
  expression?: number | string | ExpressionNode1;
}
/**
 * Replace a parameter in one system with a variable from another.
 */
export interface CouplingVariableMap {
  type: "variable_map";
  /**
   * Source variable (scoped reference, e.g., "GEOSFP.T").
   */
  from: string;
  /**
   * Target parameter (scoped reference, e.g., "SuperFast.T").
   */
  to: string;
  /**
   * How the mapping is applied.
   */
  transform: "param_to_var" | "identity" | "additive" | "multiplicative" | "conversion_factor";
  /**
   * Conversion factor (for conversion_factor transform).
   */
  factor?: number;
  /**
   * Name of an interface from the interfaces section for cross-domain coupling.
   */
  interface?: string;
  /**
   * Strategy for mapping between 0D and spatial systems.
   */
  lifting?: "pointwise" | "broadcast" | "mean" | "integral";
  description?: string;
}
/**
 * Register an Operator to run during simulation.
 */
export interface CouplingOperatorApply {
  type: "operator_apply";
  /**
   * Name of the operator (key in the operators section).
   */
  operator: string;
  description?: string;
}
/**
 * Register a callback for simulation events.
 */
export interface CouplingCallback {
  type: "callback";
  /**
   * Registered identifier for the callback.
   */
  callback_id: string;
  config?: {
    [k: string]: unknown;
  };
  description?: string;
}
/**
 * Registered functional affect handler (alternative to symbolic affects).
 */
export interface FunctionalAffect1 {
  /**
   * Registered identifier for the affect implementation.
   */
  handler_id: string;
  /**
   * State variables accessed by the handler.
   */
  read_vars: string[];
  /**
   * Parameters accessed by the handler.
   */
  read_params: string[];
  /**
   * Parameters modified by the handler (implicitly discrete parameters).
   */
  modified_params?: string[];
  /**
   * Handler-specific configuration.
   */
  config?: {
    [k: string]: unknown;
  };
}
/**
 * Spatiotemporal domain specification (DomainInfo).
 */
export interface Domain {
  /**
   * Name of the independent (time) variable.
   */
  independent_variable?: string;
  temporal?: {
    start?: string;
    end?: string;
    reference_time?: string;
  };
  /**
   * Spatial dimensions, keyed by name (e.g., lon, lat, lev).
   */
  spatial?: {
    [k: string]: SpatialDimension;
  };
  coordinate_transforms?: CoordinateTransform[];
  /**
   * Coordinate reference system (e.g., "WGS84").
   */
  spatial_ref?: string;
  initial_conditions?: InitialConditions;
  /**
   * @deprecated
   * DEPRECATED (v0.2.0, RFC §10.1): domain-level boundary_conditions is superseded by model-level boundary_conditions (models.<M>.boundary_conditions). Retained in the schema only as a transitional compatibility shim; loaders MUST emit E_DEPRECATED_DOMAIN_BC when this field is present. A follow-up release will remove this field entirely.
   */
  boundary_conditions?: DeprecatedDomainBoundaryCondition[];
  /**
   * Floating point precision.
   */
  element_type?: "Float32" | "Float64";
  /**
   * Array backend (e.g., "Array", "CuArray").
   */
  array_type?: string;
}
/**
 * Specification of a single spatial dimension.
 */
export interface SpatialDimension {
  min: number;
  max: number;
  units?: string;
  grid_spacing?: number;
}
export interface CoordinateTransform {
  id?: string;
  description?: string;
  dimensions?: string[];
}
/**
 * @deprecated
 * DEPRECATED v0.1.0 domain-level boundary condition entry. Retained for the v0.2.0 transitional window only (RFC §10.1). Loaders emit E_DEPRECATED_DOMAIN_BC when encountering it; use Model.boundary_conditions (keyed map of BoundaryCondition entries) instead.
 */
export interface DeprecatedDomainBoundaryCondition {
  type: "constant" | "zero_gradient" | "periodic" | "dirichlet" | "neumann" | "robin";
  /**
   * @minItems 1
   */
  dimensions: [string, ...string[]];
  value?: number;
  function?: string;
  robin_alpha?: number;
  robin_beta?: number;
  robin_gamma?: number;
}
/**
 * Geometric connection between two domains of potentially different dimensionality.
 */
export interface Interface {
  description?: string;
  /**
   * The two domains connected by this interface.
   *
   * @minItems 2
   * @maxItems 2
   */
  domains: [string, string];
  /**
   * Specifies shared dimensions and constraints.
   */
  dimension_mapping: {
    /**
     * Mapping of corresponding dimensions across domains, keyed by 'domain.dimension'.
     */
    shared?: {
      [k: string]: string;
    };
    /**
     * Non-shared dimensions fixed at the interface, keyed by 'domain.dimension'.
     */
    constraints?: {
      [k: string]: InterfaceConstraint;
    };
  };
  /**
   * Regridding strategy when shared dimensions differ in resolution.
   */
  regridding?: {
    /**
     * Interpolation method for regridding.
     */
    method?: "bilinear" | "conservative" | "nearest" | "patch";
    description?: string;
  };
}
/**
 * Constraint on a non-shared dimension at the interface.
 */
export interface InterfaceConstraint {
  /**
   * Where the dimension is constrained: 'min', 'max', 'boundary', or a numeric coordinate.
   */
  value: ("min" | "max" | "boundary") | number;
  description?: string;
}
/**
 * A named metric array declared on a grid (e.g., dx, dcEdge, areaCell). See §6.5.
 */
export interface GridMetricArray {
  /**
   * Tensor rank of the array: 0 = scalar (uniform spacing), 1 = 1D along a single dim, 2+ = multidimensional.
   */
  rank: number;
  /**
   * For rank=1: the dimension the array is indexed by (one of the grid's dimensions).
   */
  dim?: string;
  /**
   * For rank≥2: ordered list of dimensions the array is indexed by.
   */
  dims?: string[];
  /**
   * Optional declared shape (parameter names or integer literals per dimension). Used by connectivity/panel tables; redundant with dim/dims for metric arrays.
   */
  shape?: unknown[];
  generator: GridMetricGenerator;
}
/**
 * Per-dimension extent for cartesian or cubed_sphere grids. `n` is either an integer literal or a parameter reference naming the dimension count; `spacing` is 'uniform' or 'nonuniform' for cartesian (determines whether metric arrays are scalar or rank-1).
 */
export interface GridExtent {
  n: number | string;
  spacing?: "uniform" | "nonuniform";
}
/**
 * Unstructured-grid connectivity table (e.g., cellsOnEdge, edgesOnCell). Integer-indexed lookup produced by a mesh loader. See §6.3.
 */
export interface GridConnectivity {
  /**
   * Ordered list of dimension sizes (parameter names or integer literals). E.g., ['nEdges', 2] for cellsOnEdge.
   */
  shape: unknown[];
  rank: number;
  /**
   * Name of a data_loaders entry that supplies this table.
   */
  loader?: string;
  /**
   * Named field within the referenced loader's output.
   */
  field?: string;
  generator?: GridMetricGenerator2;
}
