source "https://rubygems.org"

# Jekyll version pinned to the GitHub Pages-compatible release.
gem "jekyll", "~> 3.10"

# Default theme.
gem "minima", "~> 2.5"

# Plugins enabled in _config.yml.
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-seo-tag", "~> 2.8"
end

# Windows and JRuby do not include zoneinfo files, so bundle the tzinfo-data
# gem and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows.
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock http_parser.rb gem to v0.6.x on JRuby builds since newer versions are
# incompatible with JRuby.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
